### ISSUE TITLE
Mac版でMouseMoveCommandが機能できない

### ISSUE THREAD

**Issue by fujimisakari** [crftwr/keyhac-win#20]
``` python
def configure(keymap):
    keymap_global = keymap.defineWindowKeymap()
    keymap_global["Alt-Shift-k"] = keymap.MouseMoveCommand(10, 0)
    keymap_global["Alt-Shift-j"] = keymap.MouseMoveCommand(-10, 0)
    keymap_global["Alt-Shift-l"] = keymap.MouseMoveCommand(0, 10)
    keymap_global["Alt-Shift-h"] = keymap.MouseMoveCommand(0, -10)
```
MacのSierraで上記のように設定して、コマンドを実行すると以下のエラーが発生します
```
ERROR : Unexpected error happened : _onKeyDown
type object 'Input' has no attribute 'getCursorPos'
Traceback (most recent call last):
  File "/Users/tom/Project/keyhac/keyhac_keymap.py", line 1037, in _onKeyDown
  File "/Users/tom/Project/keyhac/keyhac_keymap.py", line 955, in _keyAction
  File "/Users/tom/Project/keyhac/keyhac_keymap.py", line 1770, in _mouseMove
AttributeError: type object 'Input' has no attribute 'getCursorPos'
Reloaded the config file.
```
どのような対応すれば機能できますでしょうか?

**Comment by crftwr** [comment]
ドキュメントには、あまりはっきりと書かれていないのですが、
Mac版はまだマウス操作には未対応です。

**Comment by fujimisakari** [comment]
ありがとうございます!
