### ISSUE TITLE
Mac版v1.10で英数キーのワンショットモディファイアーのkeyUpでTypeError

### ISSUE THREAD

**Issue by senooken** [crftwr/keyhac-win#57]
# 環境

- Mac版のkeyhac v1.10
- OS=MacBook Air (M1, 2020) JIS配列。MacOS v14.2.1

# 手順

1 以下のconfig.pyで起動する。

```
from keyhac import *
# coding: utf-8

def configure(keymap):
    # グローバルキーマップの定義開始
    keymap_global = keymap.defineWindowKeymap()
    EISU = 0x66
    LSS_BASE = EISU
    LSS = LSS_BASE # LSS=Left Side Space (スペースの左のキー)
    ## LSSをSandSの代用にする
    # LSSをShiftにする
    keymap.replaceKey(LSS, "Shift")
    # ワンショットモディファイアとしてLSSを元のキーにに定義
    keymap_global["O-Shift"] = LSS_BASE
```

上記設定は英数キーをShiftキーにして、ワンショットモディファイアーで元の英数キー (IMEオフ) を実現する。

2 英数キーをクリック (ワンショット、押下・押上)？する。

3 以下のエラーが出る。

```
Traceback (most recent call last):
  File "/Users/tom/Project/keyhac/keyhac_keymap.py", line 1123, in _onKeyUp
  File "/Users/tom/Project/keyhac/keyhac_keymap.py", line 974, in _keyAction
TypeError
```

キーアップのタイミングで想定していないことが起こっている模様。

Macビルドをうまくするのが自分には手間だが、なんとか解決したい。

**Comment by senooken** [comment]
すみません… `EISU = "102"` とキーコードを文字列にしたら解決しました。文字列の型じゃないとだめなんですね。失礼しました…
